- data/defaults.yaml
packages:(unzip, psmisc) and set the correct patches for a 12.2 release (current patch is April 2018)
> Some minor fixes: added required packages for installation and patching

- data/defaults.yaml
- manifests/database/db_definition_template.pp
- manifests/database/db_listener.pp
- templates/General_Purpose.11.2.0.4.dbc.erb
- templates/General_Purpose.12.1.0.2.dbc.erb
- templates/General_Purpose.12.2.0.1.dbc.erb
Change-Id: I2b034dbc613cf08ba33bb792255868eaaf701fbc
> [db_definition_template] Add code to create database from template

- manifests/database/asm_listener.pp
Change-Id: I073b56b712b2b7d2fb5c984551e91357e39215ee
> [asm_listener] Call classes with user and group parameters. Closes #26

- data/defaults.yaml
- documentation/source/asm_software.md
- documentation/source/db_software.md
- documentation/source/shared/bash_profile.md
- manifests/database/asm_software.pp
Change-Id: I823ab6dc44b6d262b5cc7abd6c803b86d83b3442
> [asm_software] Add parameter bash_profile. Closes #23

- data/defaults.yaml
- documentation/source/db_software.md
- documentation/source/db_software/oper_group.md
- manifests/database/db_software.pp
Change-Id: Ibb9645a5c60a85fd64fe13f56f8fdc26e2c20554
> [db_software] Add oper_group parameter. Closes #21

- data/defaults.yaml
Change-Id: Ia2c86706e159ed6b395ea6331cdaa59361737f5b
> [asm_software] Add defaults for oper_group and ams_group

- manifests/database/asm_listener.pp
- manifests/database/db_listener.pp
Change-Id: Id1de5f842dc36e38c91544233623c2aa832dcd33
> [asm_listener/db_listener] Use the right user and group. Closes #34

- manifests/database/db_definition.pp
Change-Id: Icdf50471abef2ea4c4c199ad4330af6a53a6c92a
> [db_definition] Manage database on non-master nodes too

- templates/General_Purpose.19.3.0.0.dbc.erb
Change-Id: I26beae31ad0f9226a19ceb530e9a52dc1b91463d
> [db_definition_template] Fill template for 19c

- manifests/database/asm_software.pp
- manifests/database/db_definition.pp
- manifests/database/db_software.pp
Change-Id: I6ef04f3254f3be374df67503cfe52971c5974d5a
> [core] Add 18c support for RAC

- data/defaults.yaml
- manifests/database/db_definition_template.pp
Change-Id: I5a944393391fd075f0a377bb906eb00864d070fe
> [db_definition_template] Add log_size parameter

- manifests/database/asm_patches.pp
Change-Id: Ib57a4f692340d936e810d889a9a120f2fa50ce2c
> [asm_patches] Fix issue when no sub_patches defined

- data/defaults.yaml
- manifests/database/asm_patches.pp
- templates/patch_grid.sh.erb
Change-Id: I217d85461aa0ef05a3e3631aa407e9236855a242
> [asm_patches] Generate a script to do the patching

- manifests/database/authenticated_nodes/user_equivalence.pp
Change-Id: I05efb4aed141722944385f0436c31906723b3f9c
> [user_equivalence] Fix typo

- manifests/database/asm_patches.pp
Change-Id: I48a0c1de362334308ac430a1f1b8fa603d18a211
> [asm_patches] Fix case statement

- data/defaults.yaml
Change-Id: Iadc19a004435c118e06888a758cc0082aebc9cb4
> [asm_patches/asm_setup] Set defaults

- spec/support/acceptance/database_installer.rb
Change-Id: Id929b92c711ffa2e329e0997d19df48cad0e055e
> [spec] Fix if statement

- data/defaults.yaml
Change-Id: I57a3965c5fbac9af58fcc87efad6e9b99d286fbe
> [asm_setup] Use alias iso lookup

- manifests/database.pp
- manifests/database/asm_setup.pp
- manifests/database/asm_software.pp
Change-Id: I92a058bc6bf1949f7ebd5a318882ac7a9224b0a9
> [asm_patches] Improve ASM patching mechanism

- data/defaults.yaml
- manifests/database/asm_storage.pp
- manifests/database/asm_storage/nfs.pp
Change-Id: Ie8f76a2ba528c3dc58f1fa17ef8ef00ca6e6b06b
> [asm_storage] Remove nfs server from ora_profile

- manifests/database/firewall/firewalld.pp
Change-Id: Ic72d97b4acf247f2f5140db4e3492050c47d1c82
> [firewalld] Log dropped packets differently

- manifests/database/asm_software.pp
- manifests/database/db_software.pp
- templates/grid_addnode_18.0.0.0.rsp.erb
- templates/grid_addnode_19.0.0.0.rsp.erb
Change-Id: Ieda937f28e32f33464ff6e7329d9c1c085126281
> [asm_software] Use gridSetup.sh for version 18 and 19 to add nodes

- data/defaults.yaml
Change-Id: I79ee47aeb62cf945e41ee2c38f67104aad19ba84
> [defaults] Removed db_init_params

- data/defaults.yaml
- documentation/database/db_definition.md
- documentation/database/db_definition_template.md
- documentation/source/shared/dbdomain.md
- manifests/database/db_definition.pp
- manifests/database/db_definition_template.pp
Change-Id: I55657d5c2e86c387fcdccf718768d80325a83a97
> [db_definition_template] Expose dbdomain and add docs

- data/defaults.yaml
- data/os-major/RedHat-6.yaml
Change-Id: I0a83ad68ccea80c4f744ce44085a727148cf61e9
> [data] Add the X11 packages

- REFERENCE.md
- data/defaults.yaml
- data/os-major/RedHat-8.yaml
- documentation/database/db_patches.md
- documentation/source/database/db_patches.md
- documentation/source/database/db_patches/properties/include_ojvm.md
- documentation/source/database/db_patches/properties/level.md
- manifests/database/db_patches.pp
Change-Id: Ifeb43085d8c21d9d86b13527d714cd4446dc2621
> [db_patches] Add patch levels

- REFERENCE.md
- documentation/client/software.md
- documentation/database.md
- documentation/database/asm_listener.md
- documentation/database/db_definition.md
- documentation/database/db_definition_template.md
- documentation/database/db_listener.md
- documentation/database/db_patches.md
- documentation/database/db_software.md
- documentation/database/db_startup.md
- documentation/source/database/db_software/properties/oracle_home.md
- documentation/source/shared/oracle_base.md
- documentation/source/shared/oracle_home.md
- manifests/client/software.pp
- manifests/database.pp
- manifests/database/asm_listener.pp
- manifests/database/db_definition.pp
- manifests/database/db_definition_template.pp
- manifests/database/db_listener.pp
- manifests/database/db_patches.pp
- manifests/database/db_software.pp
- manifests/database/db_startup.pp
Change-Id: I54f72b779c10e793909b7016377c8d59fdfa2fb3
> [db_software] Enable installation of multiple ORACLE_HOME's

- documentation/database/asm_patches.md
- documentation/database/db_definition.md
- documentation/database/db_definition_template.md
- documentation/database/db_patches.md
- documentation/source/database/asm_patches.md
- documentation/source/database/db_definition.md
- documentation/source/database/db_definition_template.md
- documentation/source/database/db_patches.md
- documentation/source/database/db_patches/properties/patch_window.md
- manifests/database/asm_patches.pp
- manifests/database/db_definition.pp
- manifests/database/db_definition_template.pp
- manifests/database/db_patches.pp
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/325
> Fix warning Unknown variable: 'logoutput' in ora_profile::db_patches

- data/defaults.yaml
- data/os-major/RedHat-6.yaml
- data/os-major/RedHat-7.yaml
- data/os-major/RedHat-8.yaml
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/391
> Fix acceptance testing database

- data/defaults.yaml
- documentation/database/db_definition.md
- documentation/database/db_definition_template.md
- documentation/source/shared/dbdomain.md
- manifests/database/db_definition.pp
- manifests/database/db_definition_template.pp
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/424
> Make dbdomain also optional for `db_definition_template`

- data/defaults.yaml
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/432
> Add jul 2020 patchlevel to ora_profile

- data/defaults.yaml
- manifests/database/db_patches.pp
Change-Id: If1467e5482769dc606db30e3b6175f720c4d8c27
> Add July 2020 Release Updates for version 12.2, 18 and 19

- data/defaults.yaml
- data/os-major/RedHat-6.yaml
- data/os-major/RedHat-7.yaml
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/434
> Ora_profile doesn't ensure unzip

- manifests/oem_agent.pp
- manifests/oem_server.pp
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/552
> ora_profile::oem_agent gives error

- data/defaults.yaml
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/553
> provide a sane default fr ora_profile::oem_agent::software::temp_dir

- manifests/database/db_definition.pp
- manifests/database/db_patches.pp
Change-Id: Id0885768bac2bba59d22d77d1263a853652bc3c0
> [db_patches] Fix issue when adding new oracle_home to running system

- manifests/database/asm_patches.pp
- manifests/database/db_patches.pp
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/567
> Replace deprecated function calls in ora_profile for newer ones

- manifests/database/db_patches.pp
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/592
> Ensure datapatch is running when environment contains TWO_TASK

- .fixtures.yml
- .fixtures_latest.yml
- Gemfile
- Gemfile.lock
- metadata.json
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/673
> Certify ora_profile for Puppet 7

- manifests/database/db_patches.pp
Change-Id: Ie2d87b848b9b4e54ddd3944421129bd362910fd5
> [db_patches] Stop/Start all running listeners based on fact

- data/defaults.yaml
Change-Id: Ie7675ec13905e5ee14e85ec5f1138da1af7ab822
> [db_patches] Add OCT2020 patch levels

- manifests/database/common.pp
Change-Id: I00b1ed1eddb4eb1f8c6ddc9fb595503f5b42d3b9
> [common] Add db_control_provider

- data/defaults.yaml
- hiera.yaml
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/800
> fix lookup os_user_password oracle

- data/defaults.yaml
Change-Id: Iebc2689b7519fbefec9e9d9c18cfd045e5ee3505
> [db_patches] Add JAN2021RU patch levels

- .fixtures.yml
- .fixtures_latest.yml
- REFERENCE.md
- documentation/database.md
- documentation/database/disable_thp.md
- documentation/source/database.md
- documentation/source/database/disable_thp.md
- documentation/source/database/properties/after_disable_thp.md
- documentation/source/database/properties/before_disable_thp.md
- documentation/source/database/properties/disable_thp.md
- manifests/database.pp
- manifests/database/disable_thp.pp
- metadata.json
Change-Id: I76386b5ea74c152d16292bf14e097dd202ff101b
> [disable_thp] Added functionality

- manifests/database/db_patches.pp
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/891
> Fail when undefined patch level is used

- data/defaults.yaml
- manifests/database/cis_rules.pp
- metadata.json
- spec/default_facts.yml
- spec/fixtures/data/unit_tests.yaml
Change-Id: Ic09ceac0c0a0c3e4325dd60cb9dc245c6361fb96
> [spec] Fix spec test for new version of ora_cis

- data/defaults.yaml
Change-Id: Ieda89f587f52f144ca4532cca088e38ec80eb667
> [asm_patches/db_patches] Add April 2021 patch level

- manifests/database/db_definition.pp
- Also make sure container_database calss parameter is propagated to init.ora template
Change-Id: I71b4ae43e28a4dfc696d3f869f861dd0a777d0e4
> [db_definition] Enable dropping a database, set to ensure = absent

- data/defaults.yaml
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/935
> Add patchlevel none to ora_profile

- documentation/database/asm_storage.md
- documentation/source/database/asm_storage/properties/storage_type.md
- manifests/database/asm_storage.pp
Story details: https://app.clubhouse.io/enterprise-modules-bv/story/944
> Add storage type 'none' to ora_profile::database::asm_storage

- data/defaults.yaml
- manifests/database/asm_patches.pp
- manifests/database/db_patches.pp
Change-Id: I786664fbd98c2725fa582fa407a8a9d2f502fc4f
> [asm_patches/db_patches] Handle patch level NONE better and still catch missing levels

- data/defaults.yaml
Change-Id: Ia76bf6c651f0a40acd33760d0ad07ba598062dce
> [data] Fix typo

- data/defaults.yaml
Change-Id: I7f58cfa30b3b41748f00dbbea545fae8e1c87654
> [asm_patches/db_patches] Add support for July 2021 PSU for 12.2 and 19

- manifests/database/db_patches.pp
Change-Id: Idf50a0ea74b92f72af0f3428aa6646ec7e202055
> [db_patches] Use open_mode to determine if datapatch and utlrp should run

- manifests/database/db_patches.pp
- metadata.json
Story details: https://app.shortcut.com/enterprise-modules-bv/story/995
> let ora_profile::db_patches use all oracle_homes for opatchupdate

- spec/acceptance/secured_database_on_ora21_spec.rb
- spec/support/acceptance/database_installer.rb
Change-Id: I1f37d45646c225a28874f7f1d0a8beb300e05a86
> [spec] Fix spec test for secured database 21c

- .gitlab-ci.yml
Change-Id: I4dcaabbb031acbd13d252c915e69b0ffea0fbfc2
> [spec] Oracle 21 database Acc test

- manifests/database/em_license.pp
Story details: https://app.shortcut.com/enterprise-modules-bv/story/1077
> Fix license loading in ora_profile

- data/os-major/RedHat-8.yaml
- templates/99-oracle-asmdevices-el8.rules.epp
Story details: https://app.shortcut.com/enterprise-modules-bv/story/1127
> Add template for el8 for asm devices

- manifests/database/asm_patches.pp
- spec/classes/database/asm_patches_spec.rb
- templates/patch_grid.sh.epp
Story details: https://app.shortcut.com/enterprise-modules-bv/story/1152
Use a different directory then for db patching, should solve this issue.
> fix: [sc-1152] Permission denied when installing grid and db patches in the same run

- REFERENCE.md
- data/defaults.yaml
- data/oracle_versions/11.2.yaml
- data/oracle_versions/12.1.yaml
- data/oracle_versions/12.2.yaml
- data/oracle_versions/18.yaml
- data/oracle_versions/19.yaml
- data/oracle_versions/21.yaml
- data/os-major/RedHat-6.yaml
- data/os-major/RedHat-7.yaml
- data/os-major/RedHat-8.yaml
- documentation/database/packages.md
- documentation/oem_server.md
- documentation/source/database/packages/properties/list.md
- hiera.yaml
- manifests/oem_server.pp
- metadata.json
and move data to appropriate version file.
> Implement oracle version hiera lookup based on additional key

- data/defaults.yaml
- manifests/database/asm_patches.pp
- manifests/database/db_patches.pp
- [asm_patches/db_patches] Add check for required OPatch version [sc-1202]
> [asm_patches/db_patches] Add JAN2023RU

- data/defaults.yaml
Added APR2023RU patch for oracle 19.
Tested and works on our machines.
> added apr2023 patch for 19c
